;[
  { country: "China", cases: 80880, deaths: 3213, recovered: 67819 },
  { country: "Italy", cases: 27980, deaths: 2158, recovered: 2749 },
  { country: "Iran", cases: 14991, deaths: 853, recovered: 4590 },
  { country: "Spain", cases: 9428, deaths: 342, recovered: 530 },
  { country: "S. Korea", cases: 8236, deaths: 75, recovered: 1137 },
  { country: "Germany", cases: 7241, deaths: 15, recovered: 65 },
  { country: "France", cases: 6633, deaths: 148, recovered: 12 },
  { country: "USA", cases: 4314, deaths: 77, recovered: 73 },
  { country: "Switzerland", cases: 2353, deaths: 19, recovered: 4 },
  { country: "UK", cases: 1543, deaths: 55, recovered: 52 },
  { country: "Netherlands", cases: 1413, deaths: 24, recovered: 2 },
  { country: "Norway", cases: 1334, deaths: 3, recovered: 1 },
  { country: "Sweden", cases: 1119, deaths: 7, recovered: 1 },
  { country: "Belgium", cases: 1058, deaths: 10, recovered: 1 },
  { country: "Austria", cases: 1018, deaths: 3, recovered: 8 },
  { country: "Denmark", cases: 914, deaths: 4, recovered: 1 },
  { country: "Japan", cases: 895, deaths: 27, recovered: 144 },
  { country: "Diamond Princess", cases: 696, deaths: 7, recovered: 456 },
  { country: "Malaysia", cases: 566, deaths: 0, recovered: 42 },
  { country: "Qatar", cases: 439, deaths: 0, recovered: 4 },
  { country: "Canada", cases: 406, deaths: 4, recovered: 11 },
  { country: "Australia", cases: 375, deaths: 5, recovered: 27 },
  { country: "Greece", cases: 352, deaths: 4, recovered: 8 },
  { country: "Czechia", cases: 344, deaths: 0, recovered: 3 },
  { country: "Portugal", cases: 331, deaths: 1, recovered: 3 },
  { country: "Israel", cases: 298, deaths: 0, recovered: 4 },
  { country: "Finland", cases: 278, deaths: 0, recovered: 10 },
  { country: "Slovenia", cases: 253, deaths: 1, recovered: 0 },
  { country: "Singapore", cases: 243, deaths: 0, recovered: 109 },
  { country: "Brazil", cases: 234, deaths: 0, recovered: 2 },
  { country: "Bahrain", cases: 227, deaths: 1, recovered: 81 },
  { country: "Estonia", cases: 205, deaths: 0, recovered: 1 },
  { country: "Iceland", cases: 198, deaths: 0, recovered: 0 },
  { country: "Pakistan", cases: 184, deaths: 1, recovered: 2 },
  { country: "Ireland", cases: 170, deaths: 2, recovered: 5 },
  { country: "Romania", cases: 168, deaths: 0, recovered: 9 },
  { country: "Poland", cases: 156, deaths: 3, recovered: 0 },
  { country: "Chile", cases: 156, deaths: 0, recovered: 0 },
  { country: "Hong Kong", cases: 155, deaths: 4, recovered: 81 },
  { country: "Egypt", cases: 150, deaths: 2, recovered: 32 },
  { country: "Thailand", cases: 147, deaths: 1, recovered: 35 },
  { country: "Philippines", cases: 142, deaths: 12, recovered: 5 },
  { country: "Indonesia", cases: 134, deaths: 5, recovered: 8 },
  { country: "Iraq", cases: 133, deaths: 10, recovered: 32 },
  { country: "Saudi Arabia", cases: 133, deaths: 0, recovered: 6 },
  { country: "India", cases: 129, deaths: 2, recovered: 13 },
  { country: "Kuwait", cases: 123, deaths: 0, recovered: 9 },
  { country: "San Marino", cases: 109, deaths: 7, recovered: 4 },
  { country: "Lebanon", cases: 109, deaths: 3, recovered: 3 },
  { country: "UAE", cases: 98, deaths: 0, recovered: 23 },
  { country: "Russia", cases: 93, deaths: 0, recovered: 8 },
  { country: "Peru", cases: 86, deaths: 0, recovered: 1 },
  { country: "Luxembourg", cases: 81, deaths: 1, recovered: 0 },
  { country: "Slovakia", cases: 72, deaths: 0, recovered: 0 },
  { country: "Taiwan", cases: 67, deaths: 1, recovered: 20 },
  { country: "South Africa", cases: 64, deaths: 0, recovered: 0 },
  { country: "Bulgaria", cases: 62, deaths: 2, recovered: 0 },
  { country: "Vietnam", cases: 61, deaths: 0, recovered: 16 },
  { country: "Algeria", cases: 60, deaths: 4, recovered: 10 },
  { country: "Ecuador", cases: 58, deaths: 2, recovered: 0 },
  { country: "Croatia", cases: 57, deaths: 0, recovered: 3 },
  { country: "Serbia", cases: 57, deaths: 0, recovered: 1 },
  { country: "Argentina", cases: 56, deaths: 2, recovered: 3 },
  { country: "Panama", cases: 55, deaths: 1, recovered: 0 },
  { country: "Brunei", cases: 54, deaths: 0, recovered: 0 },
  { country: "Colombia", cases: 54, deaths: 0, recovered: 1 },
  { country: "Mexico", cases: 53, deaths: 0, recovered: 4 },
  { country: "Albania", cases: 51, deaths: 1, recovered: 0 },
  { country: "Cyprus", cases: 46, deaths: 0, recovered: 0 },
  { country: "Armenia", cases: 45, deaths: 0, recovered: 1 },
  { country: "Hungary", cases: 39, deaths: 1, recovered: 1 },
  { country: "Palestine", cases: 39, deaths: 0, recovered: 0 },
  { country: "Belarus", cases: 36, deaths: 0, recovered: 3 },
  { country: "Costa Rica", cases: 35, deaths: 0, recovered: 0 },
  { country: "Latvia", cases: 34, deaths: 0, recovered: 1 },
  { country: "Georgia", cases: 33, deaths: 0, recovered: 1 },
  { country: "Malta", cases: 30, deaths: 0, recovered: 2 },
  { country: "Morocco", cases: 29, deaths: 1, recovered: 1 },
  { country: "Moldova", cases: 29, deaths: 0, recovered: 1 },
  { country: "Sri Lanka", cases: 28, deaths: 0, recovered: 1 },
  { country: "Azerbaijan", cases: 25, deaths: 1, recovered: 6 },
  { country: "Bosnia and Herzegovina", cases: 25, deaths: 0, recovered: 2 },
  { country: "Senegal", cases: 24, deaths: 0, recovered: 2 },
  { country: "Oman", cases: 22, deaths: 0, recovered: 9 },
  { country: "Afghanistan", cases: 21, deaths: 0, recovered: 1 },
  { country: "Dominican Republic", cases: 21, deaths: 0, recovered: 0 },
  { country: "Tunisia", cases: 20, deaths: 0, recovered: 0 },
  { country: "Jordan", cases: 19, deaths: 0, recovered: 1 },
  { country: "North Macedonia", cases: 19, deaths: 0, recovered: 1 },
  { country: "Faeroe Islands", cases: 18, deaths: 0, recovered: 0 },
  { country: "Turkey", cases: 18, deaths: 0, recovered: 0 },
  { country: "Lithuania", cases: 17, deaths: 0, recovered: 1 },
  { country: "Venezuela", cases: 17, deaths: 0, recovered: 0 },
  { country: "Burkina Faso", cases: 15, deaths: 0, recovered: 0 },
  { country: "Jamaica", cases: 15, deaths: 0, recovered: 2 },
  { country: "Martinique", cases: 15, deaths: 0, recovered: 0 },
  { country: "Andorra", cases: 14, deaths: 0, recovered: 0 },
  { country: "Maldives", cases: 13, deaths: 0, recovered: 0 },
  { country: "Cambodia", cases: 12, deaths: 0, recovered: 1 },
  { country: "Macao", cases: 11, deaths: 0, recovered: 10 },
  { country: "Bolivia", cases: 11, deaths: 0, recovered: 0 },
  { country: "French Guiana", cases: 11, deaths: 0, recovered: 0 },
  { country: "Kazakhstan", cases: 10, deaths: 0, recovered: 0 },
  { country: "Réunion", cases: 9, deaths: 0, recovered: 0 },
  { country: "Guatemala", cases: 8, deaths: 1, recovered: 0 },
  { country: "New Zealand", cases: 8, deaths: 0, recovered: 0 },
  { country: "Bangladesh", cases: 8, deaths: 0, recovered: 3 },
  { country: "Paraguay", cases: 8, deaths: 0, recovered: 0 },
  { country: "Uruguay", cases: 8, deaths: 0, recovered: 0 },
  { country: "Uzbekistan", cases: 8, deaths: 0, recovered: 0 },
  { country: "Guyana", cases: 7, deaths: 1, recovered: 0 },
  { country: "Ukraine", cases: 7, deaths: 1, recovered: 0 },
  { country: "Liechtenstein", cases: 7, deaths: 0, recovered: 0 },
  { country: "Monaco", cases: 6, deaths: 0, recovered: 0 },
  { country: "Channel Islands", cases: 6, deaths: 0, recovered: 0 },
  { country: "Ghana", cases: 6, deaths: 0, recovered: 0 },
  { country: "Guadeloupe", cases: 6, deaths: 0, recovered: 0 },
  { country: "Honduras", cases: 6, deaths: 0, recovered: 0 },
  { country: "Ethiopia", cases: 5, deaths: 0, recovered: 0 },
  { country: "Puerto Rico", cases: 5, deaths: 0, recovered: 0 },
  { country: "Rwanda", cases: 5, deaths: 0, recovered: 0 },
  { country: "Cameroon", cases: 4, deaths: 0, recovered: 0 },
  { country: "Ivory Coast", cases: 4, deaths: 0, recovered: 0 },
  { country: "Cuba", cases: 4, deaths: 0, recovered: 0 },
  { country: "Trinidad and Tobago", cases: 4, deaths: 0, recovered: 0 },
  { country: "French Polynesia", cases: 3, deaths: 0, recovered: 0 },
  { country: "Gibraltar", cases: 3, deaths: 0, recovered: 1 },
  { country: "Guam", cases: 3, deaths: 0, recovered: 0 },
  { country: "Kenya", cases: 3, deaths: 0, recovered: 0 },
  { country: "St. Barth", cases: 3, deaths: 0, recovered: 0 },
  { country: "Seychelles", cases: 3, deaths: 0, recovered: 0 },
  { country: "Nigeria", cases: 2, deaths: 0, recovered: 1 },
  { country: "Aruba", cases: 2, deaths: 0, recovered: 0 },
  { country: "Curaçao", cases: 2, deaths: 0, recovered: 0 },
  { country: "DRC", cases: 2, deaths: 0, recovered: 0 },
  { country: "Namibia", cases: 2, deaths: 0, recovered: 0 },
  { country: "Saint Lucia", cases: 2, deaths: 0, recovered: 0 },
  { country: "Saint Martin", cases: 2, deaths: 0, recovered: 0 }
]
