;[
  { country: "China", cases: 80849, deaths: 3199, recovered: 66931 },
  { country: "Italy", cases: 24747, deaths: 1809, recovered: 2335 },
  { country: "Iran", cases: 13938, deaths: 724, recovered: 4590 },
  { country: "S. Korea", cases: 8162, deaths: 75, recovered: 834 },
  { country: "Spain", cases: 7798, deaths: 292, recovered: 517 },
  { country: "Germany", cases: 5795, deaths: 11, recovered: 46 },
  { country: "France", cases: 4499, deaths: 91, recovered: 12 },
  { country: "USA", cases: 3312, deaths: 62, recovered: 56 },
  { country: "Switzerland", cases: 2217, deaths: 14, recovered: 4 },
  { country: "UK", cases: 1372, deaths: 35, recovered: 18 },
  { country: "Norway", cases: 1220, deaths: 3, recovered: 1 },
  { country: "Netherlands", cases: 1135, deaths: 20, recovered: 2 },
  { country: "Sweden", cases: 1024, deaths: 3, recovered: 1 },
  { country: "Belgium", cases: 886, deaths: 4, recovered: 1 },
  { country: "Denmark", cases: 864, deaths: 2, recovered: 1 },
  { country: "Austria", cases: 860, deaths: 1, recovered: 6 },
  { country: "Japan", cases: 839, deaths: 24, recovered: 144 },
  { country: "Diamond Princess", cases: 696, deaths: 7, recovered: 456 },
  { country: "Malaysia", cases: 428, deaths: 0, recovered: 42 },
  { country: "Qatar", cases: 401, deaths: 0, recovered: 4 },
  { country: "Greece", cases: 331, deaths: 4, recovered: 8 },
  { country: "Canada", cases: 313, deaths: 1, recovered: 11 },
  { country: "Australia", cases: 300, deaths: 5, recovered: 27 },
  { country: "Czechia", cases: 253, deaths: 0, recovered: 0 },
  { country: "Portugal", cases: 245, deaths: 0, recovered: 2 },
  { country: "Finland", cases: 244, deaths: 0, recovered: 10 },
  { country: "Singapore", cases: 226, deaths: 0, recovered: 105 },
  { country: "Slovenia", cases: 219, deaths: 1, recovered: 0 },
  { country: "Bahrain", cases: 214, deaths: 0, recovered: 60 },
  { country: "Israel", cases: 213, deaths: 0, recovered: 4 },
  { country: "Estonia", cases: 171, deaths: 0, recovered: 1 },
  { country: "Iceland", cases: 171, deaths: 0, recovered: 0 },
  { country: "Hong Kong", cases: 149, deaths: 4, recovered: 81 },
  { country: "Philippines", cases: 140, deaths: 11, recovered: 2 },
  { country: "Romania", cases: 139, deaths: 0, recovered: 9 },
  { country: "Ireland", cases: 129, deaths: 2, recovered: 1 },
  { country: "Brazil", cases: 121, deaths: 0, recovered: 1 },
  { country: "Poland", cases: 119, deaths: 3, recovered: 13 },
  { country: "Indonesia", cases: 117, deaths: 5, recovered: 8 },
  { country: "Iraq", cases: 116, deaths: 10, recovered: 26 },
  { country: "Thailand", cases: 114, deaths: 1, recovered: 35 },
  { country: "Kuwait", cases: 112, deaths: 0, recovered: 9 },
  { country: "India", cases: 111, deaths: 2, recovered: 10 },
  { country: "Egypt", cases: 110, deaths: 2, recovered: 27 },
  { country: "Saudi Arabia", cases: 103, deaths: 0, recovered: 2 },
  { country: "San Marino", cases: 101, deaths: 5, recovered: 4 },
  { country: "Lebanon", cases: 99, deaths: 3, recovered: 1 },
  { country: "UAE", cases: 98, deaths: 0, recovered: 20 },
  { country: "Chile", cases: 75, deaths: 0, recovered: 0 },
  { country: "Russia", cases: 63, deaths: 0, recovered: 8 },
  { country: "Luxembourg", cases: 59, deaths: 1, recovered: 0 },
  { country: "Taiwan", cases: 59, deaths: 1, recovered: 20 },
  { country: "Vietnam", cases: 56, deaths: 0, recovered: 16 },
  { country: "Slovakia", cases: 54, deaths: 0, recovered: 0 },
  { country: "Pakistan", cases: 53, deaths: 0, recovered: 2 },
  { country: "Bulgaria", cases: 51, deaths: 2, recovered: 0 },
  { country: "South Africa", cases: 51, deaths: 0, recovered: 0 },
  { country: "Brunei", cases: 50, deaths: 0, recovered: 0 },
  { country: "Croatia", cases: 49, deaths: 0, recovered: 2 },
  { country: "Algeria", cases: 48, deaths: 4, recovered: 10 },
  { country: "Serbia", cases: 48, deaths: 0, recovered: 1 },
  { country: "Argentina", cases: 45, deaths: 2, recovered: 0 },
  { country: "Panama", cases: 43, deaths: 1, recovered: 0 },
  { country: "Peru", cases: 43, deaths: 0, recovered: 0 },
  { country: "Albania", cases: 42, deaths: 1, recovered: 0 },
  { country: "Mexico", cases: 41, deaths: 0, recovered: 4 },
  { country: "Palestine", cases: 38, deaths: 0, recovered: 0 },
  { country: "Colombia", cases: 34, deaths: 0, recovered: 0 },
  { country: "Georgia", cases: 33, deaths: 0, recovered: 1 },
  { country: "Hungary", cases: 32, deaths: 1, recovered: 1 },
  { country: "Latvia", cases: 30, deaths: 0, recovered: 1 },
  { country: "Ecuador", cases: 28, deaths: 2, recovered: 0 },
  { country: "Morocco", cases: 28, deaths: 1, recovered: 1 },
  { country: "Belarus", cases: 27, deaths: 0, recovered: 3 },
  { country: "Costa Rica", cases: 27, deaths: 0, recovered: 0 },
  { country: "Armenia", cases: 26, deaths: 0, recovered: 0 },
  { country: "Cyprus", cases: 26, deaths: 0, recovered: 0 },
  { country: "Senegal", cases: 24, deaths: 0, recovered: 2 },
  { country: "Bosnia and Herzegovina", cases: 24, deaths: 0, recovered: 0 },
  { country: "Azerbaijan", cases: 23, deaths: 1, recovered: 6 },
  { country: "Moldova", cases: 23, deaths: 0, recovered: 0 },
  { country: "Oman", cases: 22, deaths: 0, recovered: 9 },
  { country: "Malta", cases: 21, deaths: 0, recovered: 2 },
  { country: "Tunisia", cases: 20, deaths: 0, recovered: 0 },
  { country: "North Macedonia", cases: 19, deaths: 0, recovered: 1 },
  { country: "Sri Lanka", cases: 18, deaths: 0, recovered: 1 },
  { country: "Afghanistan", cases: 16, deaths: 0, recovered: 1 },
  { country: "Maldives", cases: 13, deaths: 0, recovered: 0 },
  { country: "Cambodia", cases: 12, deaths: 0, recovered: 1 },
  { country: "Lithuania", cases: 12, deaths: 0, recovered: 1 },
  { country: "Dominican Republic", cases: 11, deaths: 0, recovered: 0 },
  { country: "Faeroe Islands", cases: 11, deaths: 0, recovered: 0 },
  { country: "Macao", cases: 10, deaths: 0, recovered: 10 },
  { country: "Bolivia", cases: 10, deaths: 0, recovered: 0 },
  { country: "Jamaica", cases: 10, deaths: 0, recovered: 2 },
  { country: "Martinique", cases: 10, deaths: 0, recovered: 0 },
  { country: "Venezuela", cases: 10, deaths: 0, recovered: 0 },
  { country: "Kazakhstan", cases: 9, deaths: 0, recovered: 0 },
  { country: "Jordan", cases: 8, deaths: 0, recovered: 1 },
  { country: "New Zealand", cases: 8, deaths: 0, recovered: 0 },
  { country: "French Guiana", cases: 7, deaths: 0, recovered: 0 },
  { country: "Liechtenstein", cases: 7, deaths: 0, recovered: 0 },
  { country: "Paraguay", cases: 7, deaths: 0, recovered: 0 },
  { country: "Réunion", cases: 7, deaths: 0, recovered: 0 },
  { country: "Ghana", cases: 6, deaths: 0, recovered: 0 },
  { country: "Turkey", cases: 6, deaths: 0, recovered: 0 },
  { country: "Uruguay", cases: 6, deaths: 0, recovered: 0 },
  { country: "Andorra", cases: 5, deaths: 0, recovered: 0 },
  { country: "Bangladesh", cases: 5, deaths: 0, recovered: 2 },
  { country: "Guyana", cases: 4, deaths: 1, recovered: 0 },
  { country: "Ivory Coast", cases: 4, deaths: 0, recovered: 0 },
  { country: "Cuba", cases: 4, deaths: 0, recovered: 0 },
  { country: "Ethiopia", cases: 4, deaths: 0, recovered: 0 },
  { country: "Puerto Rico", cases: 4, deaths: 0, recovered: 0 },
  { country: "Ukraine", cases: 3, deaths: 1, recovered: 0 },
  { country: "Burkina Faso", cases: 3, deaths: 0, recovered: 0 },
  { country: "Channel Islands", cases: 3, deaths: 0, recovered: 0 },
  { country: "French Polynesia", cases: 3, deaths: 0, recovered: 0 },
  { country: "Guadeloupe", cases: 3, deaths: 0, recovered: 0 },
  { country: "Guam", cases: 3, deaths: 0, recovered: 0 },
  { country: "Honduras", cases: 3, deaths: 0, recovered: 0 },
  { country: "Kenya", cases: 3, deaths: 0, recovered: 0 },
  { country: "Monaco", cases: 2, deaths: 0, recovered: 0 },
  { country: "Nigeria", cases: 2, deaths: 0, recovered: 1 },
  { country: "Aruba", cases: 2, deaths: 0, recovered: 0 },
  { country: "Cameroon", cases: 2, deaths: 0, recovered: 0 },
  { country: "Curaçao", cases: 2, deaths: 0, recovered: 0 },
  { country: "DRC", cases: 2, deaths: 0, recovered: 0 },
  { country: "Namibia", cases: 2, deaths: 0, recovered: 0 },
  { country: "Saint Lucia", cases: 2, deaths: 0, recovered: 0 },
  { country: "Saint Martin", cases: 2, deaths: 0, recovered: 0 },
  { country: "Seychelles", cases: 2, deaths: 0, recovered: 0 },
  { country: "Trinidad and Tobago", cases: 2, deaths: 0, recovered: 0 },
  { country: "Sudan", cases: 1, deaths: 1, recovered: 0 },
  { country: "Nepal", cases: 1, deaths: 0, recovered: 1 },
  { country: "Antigua and Barbuda", cases: 1, deaths: 0, recovered: 0 },
  { country: "Bhutan", cases: 1, deaths: 0, recovered: 0 },
  { country: "Cayman Islands", cases: 1, deaths: 0, recovered: 0 },
  { country: "CAR", cases: 1, deaths: 0, recovered: 0 },
  { country: "Congo", cases: 1, deaths: 0, recovered: 0 },
  { country: "Equatorial Guinea", cases: 1, deaths: 0, recovered: 0 },
  { country: "Gabon", cases: 1, deaths: 0, recovered: 0 },
  { country: "Gibraltar", cases: 1, deaths: 0, recovered: 1 },
  { country: "Guatemala", cases: 1, deaths: 0, recovered: 0 },
  { country: "Guinea", cases: 1, deaths: 0, recovered: 0 },
  { country: "Vatican City", cases: 1, deaths: 0, recovered: 0 },
  { country: "Mauritania", cases: 1, deaths: 0, recovered: 0 },
  { country: "Mayotte", cases: 1, deaths: 0, recovered: 0 },
  { country: "Mongolia", cases: 1, deaths: 0, recovered: 0 },
  { country: "Rwanda", cases: 1, deaths: 0, recovered: 0 },
  { country: "St. Barth", cases: 1, deaths: 0, recovered: 0 },
  { country: "St. Vincent Grenadines", cases: 1, deaths: 0, recovered: 0 },
  { country: "Suriname", cases: 1, deaths: 0, recovered: 0 },
  { country: "Eswatini", cases: 1, deaths: 0, recovered: 0 },
  { country: "Togo", cases: 1, deaths: 0, recovered: 0 },
  { country: "U.S. Virgin Islands", cases: 1, deaths: 0, recovered: 0 },
  { country: "Uzbekistan", cases: 1, deaths: 0, recovered: 0 }
]
